version: '3.8'

services:
  # Service 1: The Python Flask Application
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=prod_key_secure_999
      # Important: "mongo" refers to the service name below, not localhost
      - MONGO_URI=mongodb://mongo:27017/prompt_manager_db
    depends_on:
      - mongo
    restart: always

  # Service 2: The Database
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      # Persist data even if container is destroyed
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
